@extends('layouts.home')

    @section('title','Reports')

    @section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <div class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h4 class="fw-bold">Reports</h4>
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalGenerate">+ Generate Report</button>
    </div>

    @if(session('success'))
        <script>Swal.fire({icon:'success',title:'Success',text:'{{ session('success') }}'});</script>
    @endif

    <div class="card">
        <div class="card-body table-responsive">
        <table class="table table-striped">
            <thead><tr><th>#</th><th>Type</th><th>Period</th><th>Total</th><th>Generated By</th><th>Created</th><th>Action</th></tr></thead>
            <tbody>
            @forelse($reports as $r)
                <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ ucfirst($r->report_type) }}</td>
                <td>{{ $r->period_start->format('d M Y') }} — {{ $r->period_end->format('d M Y') }}</td>
                <td>Rp {{ number_format($r->summary['total'] ?? 0,0,',','.') }}</td>
                <td>{{ $r->user->name ?? '-' }}</td>
                <td>{{ $r->created_at->format('d M Y H:i') }}</td>
                <td>
                    <a href="{{ route('reports.export', [$r->id, 'pdf']) }}" class="btn btn-sm btn-outline-danger">PDF</a>
                    <a href="{{ route('reports.export', [$r->id, 'csv']) }}" class="btn btn-sm btn-outline-success">CSV</a>
                </td>
                </tr>
            @empty
                <tr><td colspan="7" class="text-center text-muted">No reports yet</td></tr>
            @endforelse
            </tbody>
        </table>
        </div>
    </div>
    </div>

    {{-- Modal Generate --}}
    <div class="modal fade" id="modalGenerate" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form class="modal-content" action="{{ route('reports.generate') }}" method="POST">
        @csrf
        <div class="modal-header bg-primary text-white">
            <h5 class="modal-title">Generate Report</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <div class="mb-3">
            <label>Report Type</label>
            <select name="report_type" class="form-select" required>
                <option value="">Select...</option>
                <option value="sales">Sales</option>
                <option value="purchases">Purchases</option>
                <option value="stock">Stock</option>
                <option value="restock">Restock</option>
            </select>
            </div>
            <div class="mb-3">
            <label>Period Start</label>
            <input type="date" name="period_start" class="form-control" required>
            </div>
            <div class="mb-3">
            <label>Period End</label>
            <input type="date" name="period_end" class="form-control" required>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" type="submit">Generate</button>
            <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">Cancel</button>
        </div>
        </form>
    </div>
    </div>
    @endsection
