<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
  public function up(): void {
    Schema::create('reports', function (Blueprint $t) {
      $t->bigIncrements('id'); // id_report -> id
      $t->enum('report_type', ['sales','purchases','stock','restock']);
      $t->foreignId('user_id')->constrained('users'); // generated by
      $t->date('period_start')->nullable();
      $t->date('period_end')->nullable();
      $t->timestamp('created_at')->useCurrent();
      // simpan ringkasan JSON/text
      $t->json('summary')->nullable();
    });
  }
  public function down(): void {
    Schema::dropIfExists('reports');
  }
};